// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6qvuJnmtoTvwtJRvmMOdmJPJr4c1AYs',
    appId: '1:364284288036:web:800e403f762fb29fe4ccb1',
    messagingSenderId: '364284288036',
    projectId: 'duan-ea163',
    authDomain: 'duan-ea163.firebaseapp.com',
    storageBucket: 'duan-ea163.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HtVrxgSB5cgD2Kp--lxwUsZ8FscVIjs',
    appId: '1:364284288036:android:0120004848a1dae9e4ccb1',
    messagingSenderId: '364284288036',
    projectId: 'duan-ea163',
    storageBucket: 'duan-ea163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZI3bNGHtGKCwtxD4U4V2tCrxxTnMPOE',
    appId: '1:364284288036:ios:c5aa52f6fd690dc3e4ccb1',
    messagingSenderId: '364284288036',
    projectId: 'duan-ea163',
    storageBucket: 'duan-ea163.firebasestorage.app',
    iosBundleId: 'com.onlineshop.duan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZI3bNGHtGKCwtxD4U4V2tCrxxTnMPOE',
    appId: '1:364284288036:ios:c5aa52f6fd690dc3e4ccb1',
    messagingSenderId: '364284288036',
    projectId: 'duan-ea163',
    storageBucket: 'duan-ea163.firebasestorage.app',
    iosBundleId: 'com.onlineshop.duan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv6qvuJnmtoTvwtJRvmMOdmJPJr4c1AYs',
    appId: '1:364284288036:web:375548608548a8fbe4ccb1',
    messagingSenderId: '364284288036',
    projectId: 'duan-ea163',
    authDomain: 'duan-ea163.firebaseapp.com',
    storageBucket: 'duan-ea163.firebasestorage.app',
  );
}
